version: '3.8'

services:
  wife-website:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    container_name: wife-website
    restart: unless-stopped
    environment:
      - NODE_ENV=production
